version: '3.7'

services:
  app:
    image: test-socket-adapter
    deploy:
      replicas: 2
    ports:
      - 3000:3000
    environment:
      NODE_ENV: development
      SOCKET_ADAPTER: amqp
      SOCKET_PORT: 3000
      MONGO_HOST: host.docker.internal
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASS: t5t4ZpOOeW1JfPDp
      MONGO_DBNAME: mydb
      MONGO_RSNAME: rs0
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASS: t5t4ZpOOeW1JfPDp
      REDIS_DBNAME: 0
      AMQP_HOST: host.docker.internal
      AMQP_PORT: 5672
      AMQP_USER: guest
      AMQP_PASS: t5t4ZpOOeW1JfPDp